services:
  telegram-bot:
    build: .
    container_name: alex-telegram-bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Jakarta
    stdin_open: true
    tty: true
